name: Releases

on: 
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./build.sh
      - run: |
          tar -czvf libs.tar.gz libs
          tar -czvf jniLibs.tar.gz jniLibs
      - name: Upload To release 
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tdlibjson
          files: |
            jniLibs.tar.gz
            libs.tar.gz
